default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>_development

test:
  <<: *default
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: cx_web_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: cx_web_db # <-- Use the container name as the hostname
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
